version: '3'
services:
  nginx:
    image: tofran/nginx-with-substitutions-filter
    volumes:
      - ./data/config/nginx/conf.d:/etc/nginx/conf.d
    restart: always
  midjourney-proxy:
    restart: always
    image: novicezk/midjourney-proxy:2.5.5
    env_file:
      - .env
  lobe-midjourney-webui:
    restart: always
    image: ghcr.io/strrl/lobe-midjourney-webui:2024.01.30
    environment:
      - MIDJOURNEY_PROXY_URL=http://midjourney-proxy:8080
  caddy:
    image: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/config/caddy/Caddyfile:/etc/caddy/Caddyfile
